# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus


main:
    - label: Over ons
      path: blogs
    - label: Mijn Brandstof
      path: blogs
    - label: Meer Brandstof
      path: blogs
    - label: Blog
      path: blogs
    - label: Contact
      path: blogs
    - label: Aanmelden
      path: blogs
      class: menuAanmelden
    - label: Inloggen 
      path: page/
      class: menuLogIn

logo:
     - label: logo
       path: homepage 



social:   
    - label: Facebook
      link: https://facebook.com
    - label: FAQ
      link: https://twitter.com